version: "3"

services:
  # ---------------------------------
  # ZooKeeper
  # ---------------------------------
  zookeeper:
    platform: linux/amd64
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # ---------------------------------
  # Kafka broker
  # ---------------------------------
  kafka:
    platform: linux/amd64
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # Hostname your clients will use to reach Kafka
      KAFKA_ADVERTISED_HOST_NAME: localhost     # <- correct spelling
      # Connect to ZooKeeper inside the compose network
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Optional single‑broker safety tweaks
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
